import { Container } from '@mui/material'
import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import db, { Task } from '../prisma'
import { CreateTask } from '../src/features/tasks/CreateTask.component'
import { Loading } from '../src/features/tasks/Loading.component'
import { TasksList } from '../src/features/tasks/TasksList.component'
import { useAppSelector } from '../src/hooks'
import styles from '../styles/Home.module.css'

const Home: NextPage<{ tasks: Task[] }> = ({ tasks }) => {
  const status = useAppSelector(state => state.tasks.status)
  return (
    <div>
      <Head>
        <title>Tasks manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href={'/todolist'}>Todo</Link>
      <main>
        <Container maxWidth="sm">
          <h1>Tasks</h1>
          <CreateTask />
          <TasksList />
        </Container>
      </main>
      {status === 'loading' && <Loading />}
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const tasks = await db.task.findMany()
  return {
    props: {
      tasks: tasks.map(task => {
        return {
          id: task.id,
          name: task.name,
          done: task.done
        }
      })
    }, // will be passed to the page component as props
  }
}

export default Home
