import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import db, { Task } from '../prisma'
import styles from '../styles/Home.module.css'

const Home: NextPage<{tasks: Task[]}> = ({tasks}) => {
  return (
    <div>
      <Head>
        <title>Tasks manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Tasks</h1>
        <ul>
          {tasks.map(task => {
            return <li key={task.id}>{task.name}</li>
          })}
        </ul>
      </main>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const tasks = await db.task.findMany()
  return {
    props: { 
      tasks: tasks.map(task => {
        return {
          id: task.id,
          name: task.name,
          done: task.done
        }
      })
    }, // will be passed to the page component as props
  }
}

export default Home
