import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import { createStore } from 'redux'

function counterReducer(state = { value: 0 }, action: any) {
  switch (action.type) {
    case 'counter/incremented':
      return { value: state.value + 1 }
    case 'counter/decremented':
      return { value: state.value - 1 }
    default:
      return state
  }
}

let store = createStore(counterReducer)

const Test: NextPage = () => {
  const [count, setCount] = useState(0)
  useEffect(() => {
    setCount(store.getState().value)
    const unsubscribe = store.subscribe(() => setCount(store.getState().value))
    return () => {
      unsubscribe()
    }
  }, [])
  return (
    <div>
      <Head>
        <title>Redux test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Link href={'/'}>Main page</Link>
        <div>{count}</div>
      </main>
      <button onClick={() => store.dispatch({type: 'counter/incremented'})}>+</button>
      <button onClick={() => store.dispatch({type: 'counter/decremented'})}>-</button>
    </div>
  )
}

export default Test