import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import { useSelector, useDispatch } from 'react-redux'
import { decrement, increment, incrementByAmount } from '../src/features/counter/counterSlice'
import { useAppDispatch, useAppSelector } from '../src/hooks'
import { AppDispatch, RootState } from '../src/store/store'

const Toolkit: NextPage = () => {
  const count = useAppSelector(state => state.counter.value)
  const dispatch = useAppDispatch()
  const [amount, setAmount] = useState(2)
  return (
    <div>
      <Head>
        <title>Redux test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Link href={'/'}>Main page</Link>
        <div>{count}</div>
      </main>
      <button onClick={() => dispatch(increment())}>+</button>
      <button onClick={() => dispatch(decrement())}>-</button>
      <br />
      <input value={amount} onChange={e => {
        const newAmount = parseInt(e.target.value)
        if (!isNaN(newAmount)) setAmount(newAmount)
      }} />
      <button onClick={() => dispatch(incrementByAmount(amount))}>Amount +</button>
    </div>
  )
}

export default Toolkit